### ISSUE TITLE
Composer Install broken

### ISSUE THREAD

**Issue by svandragt** [mapkyca/known-vagrant#3]
I was hoping to do some plugin dev, and assumed using this repo is the easiest way to get going. After setting up known-vagrant and installing Known is instructed, the box boots but visiting http://withknown says:

>  Your Known installation is incomplete!
> 
> It looks like you're running Known directly from a GitHub checkout. You need to run "composer install" to fetch other required packages!

I expected the ansible scripts to do this already, but attempting to run this manually also fails from within the vm from /vagrant/Known/:
> Installing dependencies (including require-dev) from lock file
> 
>                                                                                            
>   [ErrorException]                                                                         
>   "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
>                                                                                            

Some people suggest updating composer but composer self-update is not available, even after reinstalling composer. php:

> PHP 7.3.8-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:51:47) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.8-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Any pointers?

**Comment by mapkyca** [comment]
Ansible scripts were written before the move to composer, and I've not had a chance to update them. PRs welcome.

As for your problem I think the distro version of composer is a little old. Try getting a composer.phar from https://getcomposer.org and using that instead.
